apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 150291371252.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 150291371252.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: "30065134"
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
